apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: management-frontend-pdb
  namespace: app
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: management-frontend
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: management-backend-pdb
  namespace: app
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: management-backend
