apiVersion: v1
kind: Secret
metadata:
  name: rds-secret
  namespace: app
type: Opaque
stringData:
  DB_USERNAME: "admin"
  DB_PASSWORD: "**********"
  DB_HOST: "*************"
  DB_PORT: "3306"
  DB_DATABASE: "kubeadm_dev_db"
  DB_DIALECT: "mysql"
